// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgIKP5E3_RzwKuxaV4A5hOyVdVr0VKk4',
    appId: '1:740619589260:web:1dba2dd2d45e0273950da9',
    messagingSenderId: '740619589260',
    projectId: 'signin-flutter-b60ba',
    authDomain: 'signin-flutter-b60ba.firebaseapp.com',
    storageBucket: 'signin-flutter-b60ba.appspot.com',
    measurementId: 'G-BE548YGCV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPhffj9c4HeFRZngcJ__xZKIUwom8tDtw',
    appId: '1:740619589260:android:a11f2b853f0ced69950da9',
    messagingSenderId: '740619589260',
    projectId: 'signin-flutter-b60ba',
    storageBucket: 'signin-flutter-b60ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXbqfUFWl1JjlQkhpFf1-PgcBtInoSv8s',
    appId: '1:740619589260:ios:90b6a7cc1e16e52e950da9',
    messagingSenderId: '740619589260',
    projectId: 'signin-flutter-b60ba',
    storageBucket: 'signin-flutter-b60ba.appspot.com',
    iosClientId: '740619589260-1m4avmrhbsbrfo1gep8e0p2o37l17cn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterEfficiencyTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXbqfUFWl1JjlQkhpFf1-PgcBtInoSv8s',
    appId: '1:740619589260:ios:90b6a7cc1e16e52e950da9',
    messagingSenderId: '740619589260',
    projectId: 'signin-flutter-b60ba',
    storageBucket: 'signin-flutter-b60ba.appspot.com',
    iosClientId: '740619589260-1m4avmrhbsbrfo1gep8e0p2o37l17cn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterEfficiencyTool',
  );
}
